### PR TITLE
[GCI-5] Update .gitignore file

### PR DESCRIPTION
**Pull request by SquidDev**
From [this task](https://issues.openmrs.org/browse/GCI-5).

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Is this associated with an open task?

**Comment by SquidDev** [comment]
Sorry. The melange task is here:https://www.google-melange.com/gci/task/view/google/gci2014/5811542629023744

**Comment by robbyoconnor** [comment]
Approved as part of [GCI 2014](https://www.google-melange.com/gci/task/view/google/gci2014/5811542629023744)

**Comment by SquidDev** [comment]
Thanks! :smile:

**Comment by robbyoconnor** [comment]
Now change the state of the task...

**Comment by robbyoconnor** [comment]
@SquidDev....

**Pull request merged**
